on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Node Cache
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Wasm Pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: Build with wasm-pack
        run: wasm-pack build --target=web

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
