on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Node Cache
        uses: actions/cache@v4
        with:
          path: ~/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Rust Unit Tests
        run: cargo test --verbose

      - name: Install Wasm Pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: Build with wasm-pack
        run: ./build.sh

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Integration Tests
        run: cd test && npm install && npm test
